# Generated by Django 4.2.2 on 2023-06-17 19:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pretty_id', models.IntegerField()),
                ('status', models.CharField(choices=[('WT', 'Ждем ответ от Hidden Kitchen'), ('AC', 'Ваш заказ готовится'), ('RD', 'Ваш заказ готов и ждет курьера'), ('DL', 'Ваш заказ будет доставлен в течение X минут'), ('DN', 'Заказ доставлен'), ('ER', 'Произошла ошибка'), ('CL', 'Заказ отменен')], default='wt', max_length=2)),
                ('items', models.JSONField()),
                ('is_inside', models.BooleanField()),
                ('is_cash_payment', models.BooleanField()),
                ('price', models.IntegerField()),
                ('user_cash', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('review', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('err_msg', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
