name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Save Docker image to a tarball
        run: docker save my-app | gzip > my-app.tar.gz

      - name: Upload Docker image tarball
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: my-app.tar.gz

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "Deploying to server..."
          # Install SSH client if not already present
          sudo apt-get update && sudo apt-get install -y openssh-client
          # Download the Docker image tarball
          curl -O https://github.com/${{ github.repository }}/releases/download/${{ github.sha }}/my-app.tar.gz
          # Connect to the server and deploy
          sshpass -p $SERVER_PASSWORD ssh $SERVER_USER@$SERVER_IP << EOF
            docker load < my-app.tar.gz
            docker run -d --rm my-app
          EOF
